version: '2.4'
services:
  bot:
    build: https://github.com/Craeckie/KIT-Sitzplatzreservierung.git
    environment:
      BOT_TOKEN: "123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11" # your bot token
      REDIS_HOST: "redis"
      TZ: "Europe/Berlin"
      PROXY: "socks5h://tor:9050" # proxy container, optional

    networks:
      - internal
      - external

    restart: unless-stopped

    mem_limit: 192M
    cpu_shares: 128
    blkio_config:
      weight: 200

  redis:
    image: redis:alpine
    volumes:
      - ./redis-data:/data
    networks:
      - internal

    mem_limit: 256M
    cpu_shares: 256
    blkio_config:
      weight: 200

networks:
  internal:
    internal: true
  external:
